In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost
import optuna

from sklearn.model_selection import train_test_split,StratifiedKFold
from sklearn.metrics import accuracy_score,classification_report,roc_auc_score,roc_curve,f1_score
from xgboost import XGBClassifier,callback

In [2]:
train = pd.read_csv('/kaggle/input/competitions/playground-series-s6e3/train.csv')
test = pd.read_csv('/kaggle/input/competitions/playground-series-s6e3/test.csv')

In [3]:
train.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [4]:
test_id = test['id']

In [5]:
train.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [6]:
train_cols = train.select_dtypes(['object']).columns
test_cols = test.select_dtypes(['object']).columns

In [7]:
train = pd.get_dummies(data=train,columns=train_cols[:-1],drop_first=True,dtype=int)
test = pd.get_dummies(data=test,columns=test_cols,drop_first=True,dtype=int)

In [8]:
train.drop(columns=['id'],inplace = True)
test.drop(columns=['id'],inplace = True)

In [9]:
train['Churn'] = train['Churn'].map({'No':0,'Yes':1})

In [10]:
X = train.drop(columns=['Churn'])
y = train['Churn']

In [11]:
# model = XGBClassifier(
#     learning_rate=0.02,
#     tree_method='hist',
#     random_state=42,
#     subsample=0.8,
#     colsample_bytree=0.4,
#     n_estimators=3300,
#     max_depth=5,
#     gamma=0.3,
#     min_child_weight=6,
#     device='cuda',
#     early_stopping_rounds=150,
#     reg_alpha=3,
#     enable_categorical=True
# )

In [12]:
# oof_preds = np.zeros(len(X)) 
# # test_preds_total: To store the average predictions for the test set (for submission)
# test_preds_total = np.zeros(len(test))
# # Initialize the S-KFold strategy
# n_s = 12
# skf = StratifiedKFold(n_splits=n_s, shuffle=True, random_state=42)
# for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
#     X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
#     y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]
    
#     model.fit(
#         X_train, y_train,
#         eval_set=[(X_val, y_val)],
#         verbose=0
#     )
    
#     pre_y_xgb = model.predict_proba(X_val)[:, 1]
#     print(f'Score of Fold {fold} XGB: {roc_auc_score(y_val,pre_y_xgb):.5f} %')

    

#     test_preds_total += model.predict_proba(test)[:, 1]/n_s
#     oof_preds[val_idx] = pre_y_xgb
#     print(f"Fold {fold} finished.")

In [13]:
# print(f'XGB Train score:{roc_auc_score(y,oof_preds):.5f}')

In [14]:
# preditions = test_preds_total

In [15]:
# df = pd.DataFrame({
#     'id':test_id,
#     'Churn':preditions
# })

In [16]:
# df.head()

In [17]:
# df.to_csv('sub_3.csv',index=False)

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=42,stratify=y)

In [19]:
def objective(trial):
  params = {
      "objective":"binary:logistic",
      "eval_metric":"auc",
      "tree_method":"hist",
      "random_state":42,
      "verbosity":0,
      "device":"cuda",
      "max_depth":trial.suggest_int("max_depth",3,12,step=1),
      "learning_rate":trial.suggest_float("learning_rate",1e-3,0.1,log=True),
      "min_child_weight":trial.suggest_int("min_child_weight",1,20),
      "gamma":trial.suggest_float("gamma",0,5),
      "subsample":trial.suggest_float("subsample",0.5,1.0),
      "colsample_bytree":trial.suggest_float("colsample_bytree",0.5,1.0),
      "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
      "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
      "scale_pos_weight": trial.suggest_float("scale_pos_weight", 0.5, 10.0)
  }

  kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
  scores = []
  best_iters = []
  for fold, (train_idx, valid_idx) in enumerate(kf.split(X_train,y_train)):
        X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[valid_idx]
        y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[valid_idx]

        model = XGBClassifier(
            **params,
            n_estimators=5000,
            callbacks=[
                callback.EarlyStopping(
                    rounds=100,
                    save_best=True
                )
            ]
        )
        model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)], verbose=False)

        proba = model.predict_proba(X_val)[:, 1]
        score = roc_auc_score(y_val, proba)
        scores.append(score)

        best_iters.append(model.best_iteration + 1 if model.best_iteration is not None else 5000)
        trial.report(np.mean(scores), step=fold)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()
  trial.set_user_attr("avg_best_iteration", float(np.mean(best_iters)))
  return float(np.mean(scores))

In [20]:
study = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42),
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=5)
)
study.optimize(objective,n_trials=50)

[I 2026-03-24 08:10:23,425] A new study created in memory with name: no-name-535ec218-5796-4a81-8d6f-5740a312a087
[I 2026-03-24 08:10:38,079] Trial 0 finished with value: 0.9156294896969323 and parameters: {'max_depth': 6, 'learning_rate': 0.07969454818643935, 'min_child_weight': 15, 'gamma': 2.993292420985183, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.5779972601681014, 'reg_alpha': 3.3323645788192616e-08, 'reg_lambda': 0.6245760287469893, 'scale_pos_weight': 6.210592611560483}. Best is trial 0 with value: 0.9156294896969323.
[I 2026-03-24 08:11:38,112] Trial 1 finished with value: 0.9130611540210897 and parameters: {'max_depth': 10, 'learning_rate': 0.0010994335574766201, 'min_child_weight': 20, 'gamma': 4.162213204002109, 'subsample': 0.6061695553391381, 'colsample_bytree': 0.5909124836035503, 'reg_alpha': 4.4734294104626844e-07, 'reg_lambda': 5.472429642032198e-06, 'scale_pos_weight': 5.48518610050626}. Best is trial 0 with value: 0.9156294896969323.
[I 2026-03-24 08:13:51,037] Trial 2 finished with value: 0.9159725015647288 and parameters: {'max_depth': 7, 'learning_rate': 0.0038234752246751854, 'min_child_weight': 13, 'gamma': 0.6974693032602092, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.6831809216468459, 'reg_alpha': 0.00012724181576752517, 'reg_lambda': 0.1165691561324743, 'scale_pos_weight': 2.3969009305044175}. Best is trial 2 with value: 0.9159725015647288.
[I 2026-03-24 08:14:36,567] Trial 3 finished with value: 0.9157648313395151 and parameters: {'max_depth': 8, 'learning_rate': 0.015304852121831466, 'min_child_weight': 1, 'gamma': 3.0377242595071916, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'reg_alpha': 3.4671276804481113, 'reg_lambda': 4.905556676028774, 'scale_pos_weight': 8.17977480710638}. Best is trial 2 with value: 0.9159725015647288.
[I 2026-03-24 08:14:43,116] Trial 4 finished with value: 0.9092103205437189 and parameters: {'max_depth': 6, 'learning_rate': 0.0015679933916723015, 'min_child_weight': 14, 'gamma': 2.2007624686980067, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351, 'reg_alpha': 2.039373116525212e-08, 'reg_lambda': 1.527156759251193, 'scale_pos_weight': 2.9584098252001607}. Best is trial 2 with value: 0.9159725015647288.
[I 2026-03-24 08:16:49,066] Trial 5 finished with value: 0.9153010656107995 and parameters: {'max_depth': 9, 'learning_rate': 0.004201672054372531, 'min_child_weight': 11, 'gamma': 2.7335513967163982, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'reg_alpha': 0.09466630153726856, 'reg_lambda': 2.854239907497756, 'scale_pos_weight': 9.000859829062664}. Best is trial 2 with value: 0.9159725015647288.
[I 2026-03-24 08:17:01,462] Trial 6 finished with value: 0.9149634792161029 and parameters: {'max_depth': 8, 'learning_rate': 0.06978281265126034, 'min_child_weight': 2, 'gamma': 0.979914312095726, 'subsample': 0.522613644455269, 'colsample_bytree': 0.6626651653816322, 'reg_alpha': 3.148441347423712e-05, 'reg_lambda': 2.7678419414850017e-06, 'scale_pos_weight': 8.373006336943329}. Best is trial 2 with value: 0.9159725015647288.
[I 2026-03-24 08:18:54,220] Trial 7 finished with value: 0.9157584301392518 and parameters: {'max_depth': 6, 'learning_rate': 0.0036464395589807202, 'min_child_weight': 11, 'gamma': 0.7046211248738132, 'subsample': 0.9010984903770198, 'colsample_bytree': 0.5372753218398854, 'reg_alpha': 7.620481786158549, 'reg_lambda': 0.08916674715636537, 'scale_pos_weight': 2.387798974574638}. Best is trial 2 with value: 0.9159725015647288.
[I 2026-03-24 08:19:46,767] Trial 8 finished with value: 0.9159196093624283 and parameters: {'max_depth': 3, 'learning_rate': 0.04274869455295218, 'min_child_weight': 15, 'gamma': 3.6450358402049368, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.5370223258670452, 'reg_alpha': 1.683416412018213e-05, 'reg_lambda': 1.1036250149900698e-07, 'scale_pos_weight': 8.699482545818139}. Best is trial 2 with value: 0.9159725015647288.
[I 2026-03-24 08:21:40,887] Trial 9 finished with value: 0.9154330514826723 and parameters: {'max_depth': 9, 'learning_rate': 0.004589824181495649, 'min_child_weight': 2, 'gamma': 1.554911608578311, 'subsample': 0.6625916610133735, 'colsample_bytree': 0.864803089169032, 'reg_alpha': 0.005470376807480391, 'reg_lambda': 0.9658611176861268, 'scale_pos_weight': 4.986041789038518}. Best is trial 2 with value: 0.9159725015647288.
[I 2026-03-24 08:22:38,772] Trial 10 finished with value: 0.9150643954429866 and parameters: {'max_depth': 12, 'learning_rate': 0.013454010047783632, 'min_child_weight': 6, 'gamma': 0.08980937807409806, 'subsample': 0.7512656088373981, 'colsample_bytree': 0.7606165441675251, 'reg_alpha': 0.0009327366933736893, 'reg_lambda': 0.00413763088103683, 'scale_pos_weight': 0.8791215893351063}. Best is trial 2 with value: 0.9159725015647288.
[I 2026-03-24 08:23:39,888] Trial 11 finished with value: 0.9156208382701555 and parameters: {'max_depth': 3, 'learning_rate': 0.03310776927477497, 'min_child_weight': 18, 'gamma': 4.6654189930328895, 'subsample': 0.9452700149345249, 'colsample_bytree': 0.6811526215520515, 'reg_alpha': 1.7924530840452524e-05, 'reg_lambda': 4.694221200463742e-08, 'scale_pos_weight': 9.981499692709594}. Best is trial 2 with value: 0.9159725015647288.
[I 2026-03-24 08:24:44,907] Trial 12 finished with value: 0.915998372851235 and parameters: {'max_depth': 3, 'learning_rate': 0.03159488591670325, 'min_child_weight': 15, 'gamma': 3.704786156841094, 'subsample': 0.8280382521790727, 'colsample_bytree': 0.6379152644536915, 'reg_alpha': 1.133211584423587e-05, 'reg_lambda': 0.00042371132433695466, 'scale_pos_weight': 3.7506563859914337}. Best is trial 12 with value: 0.915998372851235.
[I 2026-03-24 08:26:10,302] Trial 13 finished with value: 0.9158361738647229 and parameters: {'max_depth': 4, 'learning_rate': 0.007759293443235479, 'min_child_weight': 7, 'gamma': 2.039294159774773, 'subsample': 0.7712276854425826, 'colsample_bytree': 0.6714129799598364, 'reg_alpha': 1.4927751499807082e-06, 'reg_lambda': 0.000816529455213191, 'scale_pos_weight': 3.6416715571475358}. Best is trial 12 with value: 0.915998372851235.
[I 2026-03-24 08:26:42,401] Trial 14 finished with value: 0.9151820493826957 and parameters: {'max_depth': 5, 'learning_rate': 0.03332103333641685, 'min_child_weight': 13, 'gamma': 4.980084946806068, 'subsample': 0.8155421717694826, 'colsample_bytree': 0.7734488559501566, 'reg_alpha': 0.00033884142130210365, 'reg_lambda': 0.015936847132187043, 'scale_pos_weight': 0.9753206440212283}. Best is trial 12 with value: 0.915998372851235.
[I 2026-03-24 08:31:03,019] Trial 15 finished with value: 0.9150656930212341 and parameters: {'max_depth': 12, 'learning_rate': 0.0023170260508690484, 'min_child_weight': 9, 'gamma': 3.948576340506786, 'subsample': 0.675760829066606, 'colsample_bytree': 0.8449184992167584, 'reg_alpha': 0.008221926901805256, 'reg_lambda': 6.021858159982118e-05, 'scale_pos_weight': 4.184470449924096}. Best is trial 12 with value: 0.915998372851235.
[I 2026-03-24 08:32:08,583] Trial 16 finished with value: 0.9159841888081445 and parameters: {'max_depth': 5, 'learning_rate': 0.01924211754471266, 'min_child_weight': 17, 'gamma': 3.4723458005570724, 'subsample': 0.8302996229142291, 'colsample_bytree': 0.6289222866088006, 'reg_alpha': 7.12484918926443e-07, 'reg_lambda': 8.145203202357507e-05, 'scale_pos_weight': 2.021171956825361}. Best is trial 12 with value: 0.915998372851235.
[I 2026-03-24 08:33:20,709] Trial 17 finished with value: 0.9159533665379925 and parameters: {'max_depth': 4, 'learning_rate': 0.01651644444134928, 'min_child_weight': 18, 'gamma': 3.4512347972961317, 'subsample': 0.824766498931953, 'colsample_bytree': 0.6177310163032171, 'reg_alpha': 1.0131207604151506e-06, 'reg_lambda': 4.220497524471038e-05, 'scale_pos_weight': 6.876751189830244}. Best is trial 12 with value: 0.915998372851235.
[I 2026-03-24 08:34:22,684] Trial 18 finished with value: 0.9157575665157424 and parameters: {'max_depth': 4, 'learning_rate': 0.02420198338391351, 'min_child_weight': 17, 'gamma': 4.268421588478095, 'subsample': 0.8359976009145605, 'colsample_bytree': 0.6185130743046794, 'reg_alpha': 1.3788611439902617e-07, 'reg_lambda': 0.00022163473160045685, 'scale_pos_weight': 2.0617690072948616}. Best is trial 12 with value: 0.915998372851235.
[I 2026-03-24 08:35:39,778] Trial 19 finished with value: 0.9154630136407089 and parameters: {'max_depth': 5, 'learning_rate': 0.007212001405714605, 'min_child_weight': 17, 'gamma': 3.3805498772353246, 'subsample': 0.9779126367338762, 'colsample_bytree': 0.7231610042250181, 'reg_alpha': 6.975224418284354e-06, 'reg_lambda': 1.229919564892088e-06, 'scale_pos_weight': 4.081942444027929}. Best is trial 12 with value: 0.915998372851235.
[I 2026-03-24 08:36:22,238] Trial 20 finished with value: 0.91615759284667 and parameters: {'max_depth': 3, 'learning_rate': 0.04660178476875964, 'min_child_weight': 20, 'gamma': 2.406514832031015, 'subsample': 0.7061148285810195, 'colsample_bytree': 0.8199212859905155, 'reg_alpha': 2.1865935944359215e-06, 'reg_lambda': 0.0007628495263552133, 'scale_pos_weight': 1.6122823551643242}. Best is trial 20 with value: 0.91615759284667.
[I 2026-03-24 08:36:56,068] Trial 21 finished with value: 0.9161113333308004 and parameters: {'max_depth': 3, 'learning_rate': 0.0529473465871101, 'min_child_weight': 19, 'gamma': 2.4474395438686747, 'subsample': 0.7119633107686136, 'colsample_bytree': 0.844046546593187, 'reg_alpha': 2.544250755753127e-06, 'reg_lambda': 0.0016378896032240853, 'scale_pos_weight': 1.6802036232586466}. Best is trial 20 with value: 0.91615759284667.
[I 2026-03-24 08:37:29,621] Trial 22 finished with value: 0.9161755219426011 and parameters: {'max_depth': 3, 'learning_rate': 0.061934012867489695, 'min_child_weight': 20, 'gamma': 2.2411574665888407, 'subsample': 0.707289201615861, 'colsample_bytree': 0.8263360537896282, 'reg_alpha': 3.7623986467756278e-06, 'reg_lambda': 0.0017930811732582823, 'scale_pos_weight': 1.4692147700290312}. Best is trial 22 with value: 0.9161755219426011.
[I 2026-03-24 08:38:03,281] Trial 23 finished with value: 0.9162102618543007 and parameters: {'max_depth': 3, 'learning_rate': 0.060132995548464005, 'min_child_weight': 20, 'gamma': 1.7376890016504767, 'subsample': 0.7051984933566552, 'colsample_bytree': 0.8464426291481142, 'reg_alpha': 1.5439201662136474e-07, 'reg_lambda': 0.003562097742894916, 'scale_pos_weight': 1.2229772569882722}. Best is trial 23 with value: 0.9162102618543007.
[I 2026-03-24 08:38:20,966] Trial 24 finished with value: 0.9162104682973672 and parameters: {'max_depth': 4, 'learning_rate': 0.09973026847681425, 'min_child_weight': 20, 'gamma': 1.5505082302959585, 'subsample': 0.7085857604114407, 'colsample_bytree': 0.8984243696584137, 'reg_alpha': 8.119721822765917e-08, 'reg_lambda': 0.017439467770420415, 'scale_pos_weight': 0.8185319094641558}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:38:44,731] Trial 25 finished with value: 0.916151039226407 and parameters: {'max_depth': 4, 'learning_rate': 0.08826300848776437, 'min_child_weight': 20, 'gamma': 1.7563931011015703, 'subsample': 0.7186112178111818, 'colsample_bytree': 0.9145942595193253, 'reg_alpha': 1.2062276910054757e-07, 'reg_lambda': 0.0065484706708472265, 'scale_pos_weight': 0.5121205788456732}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:39:03,842] Trial 26 finished with value: 0.9161246766930835 and parameters: {'max_depth': 5, 'learning_rate': 0.05999456675643036, 'min_child_weight': 18, 'gamma': 1.4400408293703735, 'subsample': 0.7782615412752821, 'colsample_bytree': 0.9177603472684349, 'reg_alpha': 1.0931308096924014e-08, 'reg_lambda': 0.035513295619295775, 'scale_pos_weight': 1.1794730119099812}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:39:23,386] Trial 27 finished with value: 0.9160224295005527 and parameters: {'max_depth': 4, 'learning_rate': 0.07520663429792947, 'min_child_weight': 16, 'gamma': 1.2545165445443236, 'subsample': 0.6845018797090197, 'colsample_bytree': 0.9008843495227655, 'reg_alpha': 1.2840129450567255e-07, 'reg_lambda': 0.3151259553586801, 'scale_pos_weight': 2.714308325633973}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:39:47,737] Trial 28 finished with value: 0.9159932595733059 and parameters: {'max_depth': 3, 'learning_rate': 0.09276916638825645, 'min_child_weight': 19, 'gamma': 2.028751630627679, 'subsample': 0.6314980604814028, 'colsample_bytree': 0.9688544564551294, 'reg_alpha': 9.819180180412777e-08, 'reg_lambda': 0.014147700720486028, 'scale_pos_weight': 3.3108651374981495}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:40:08,160] Trial 29 finished with value: 0.9156459744623453 and parameters: {'max_depth': 7, 'learning_rate': 0.09652512233078718, 'min_child_weight': 20, 'gamma': 2.8155339621655626, 'subsample': 0.7312206414739781, 'colsample_bytree': 0.8075819986771255, 'reg_alpha': 2.8762271953486556e-08, 'reg_lambda': 0.0035385478822007443, 'scale_pos_weight': 0.5409728340976251}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:40:48,929] Trial 30 finished with value: 0.9161236511139826 and parameters: {'max_depth': 5, 'learning_rate': 0.023843513207250165, 'min_child_weight': 16, 'gamma': 0.2606871031934501, 'subsample': 0.7856856163905417, 'colsample_bytree': 0.9387516248849591, 'reg_alpha': 3.372895904975852e-07, 'reg_lambda': 1.8340074302082052e-05, 'scale_pos_weight': 1.4904456922746032}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:41:32,540] Trial 31 finished with value: 0.9161954099686911 and parameters: {'max_depth': 3, 'learning_rate': 0.04911771459532073, 'min_child_weight': 20, 'gamma': 2.3919941172783195, 'subsample': 0.7039147285447092, 'colsample_bytree': 0.8028526498610735, 'reg_alpha': 4.23137663595567e-06, 'reg_lambda': 0.0011946189742886323, 'scale_pos_weight': 1.505318628277379}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:41:57,208] Trial 32 finished with value: 0.9161993804904973 and parameters: {'max_depth': 4, 'learning_rate': 0.06297217030882271, 'min_child_weight': 19, 'gamma': 1.8051542666750071, 'subsample': 0.6325744181146882, 'colsample_bytree': 0.8836319874423045, 'reg_alpha': 0.00010402418419586584, 'reg_lambda': 0.06673989046009825, 'scale_pos_weight': 1.338788072067213}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:42:18,643] Trial 33 finished with value: 0.9156856861207261 and parameters: {'max_depth': 6, 'learning_rate': 0.03897190798211462, 'min_child_weight': 19, 'gamma': 1.7597059827575594, 'subsample': 0.6300470919612998, 'colsample_bytree': 0.8792208716997852, 'reg_alpha': 5.871628529790298e-05, 'reg_lambda': 0.20654894020766282, 'scale_pos_weight': 6.808882730631831}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:42:43,122] Trial 34 finished with value: 0.9161084118622298 and parameters: {'max_depth': 4, 'learning_rate': 0.059893814188579815, 'min_child_weight': 18, 'gamma': 1.016606270982213, 'subsample': 0.5484115546855831, 'colsample_bytree': 0.7845194789596303, 'reg_alpha': 0.00017610454899984518, 'reg_lambda': 0.045100702593654035, 'scale_pos_weight': 2.194339558678746}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:43:03,982] Trial 35 finished with value: 0.915991594088253 and parameters: {'max_depth': 4, 'learning_rate': 0.07470960793675689, 'min_child_weight': 13, 'gamma': 1.810998227457783, 'subsample': 0.6194816640267157, 'colsample_bytree': 0.949505708295669, 'reg_alpha': 3.281844328868254e-07, 'reg_lambda': 0.015171093494834439, 'scale_pos_weight': 3.0267149403393203}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:43:34,008] Trial 36 finished with value: 0.9153301699651589 and parameters: {'max_depth': 11, 'learning_rate': 0.025288610430272345, 'min_child_weight': 19, 'gamma': 3.0143434441303247, 'subsample': 0.6630849559755043, 'colsample_bytree': 0.7196613292864377, 'reg_alpha': 4.3041443957202017e-08, 'reg_lambda': 0.5731695848150924, 'scale_pos_weight': 4.656726386651686}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:43:57,919] Trial 37 finished with value: 0.9159116756875603 and parameters: {'max_depth': 5, 'learning_rate': 0.04881409170785379, 'min_child_weight': 16, 'gamma': 2.6593653400659876, 'subsample': 0.7434252648860278, 'colsample_bytree': 0.8685095412465906, 'reg_alpha': 0.0011967852670515676, 'reg_lambda': 6.8657275946606875, 'scale_pos_weight': 5.988563097599837}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:44:09,176] Trial 38 finished with value: 0.915827083268472 and parameters: {'max_depth': 7, 'learning_rate': 0.09884741298401992, 'min_child_weight': 20, 'gamma': 1.3139101289866126, 'subsample': 0.604460571182802, 'colsample_bytree': 0.7967547381285492, 'reg_alpha': 0.10598826474983923, 'reg_lambda': 0.0002209336962046486, 'scale_pos_weight': 1.0978517883347216}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:44:53,536] Trial 39 finished with value: 0.9160576860127756 and parameters: {'max_depth': 3, 'learning_rate': 0.039310602372223, 'min_child_weight': 14, 'gamma': 0.5917870107680925, 'subsample': 0.568682526205297, 'colsample_bytree': 0.8937161172989719, 'reg_alpha': 5.456960444450377e-05, 'reg_lambda': 0.05914621203030078, 'scale_pos_weight': 2.6266839331666905}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:45:07,493] Trial 40 finished with value: 0.9159223415823867 and parameters: {'max_depth': 6, 'learning_rate': 0.07670032403259378, 'min_child_weight': 19, 'gamma': 0.9976877023303949, 'subsample': 0.6521550278993374, 'colsample_bytree': 0.8434718425145458, 'reg_alpha': 1.0305050066959539e-08, 'reg_lambda': 0.12255009250368326, 'scale_pos_weight': 1.8818770864498813}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:45:41,793] Trial 41 finished with value: 0.9161886825724903 and parameters: {'max_depth': 3, 'learning_rate': 0.059364531128172304, 'min_child_weight': 20, 'gamma': 2.1592197787684055, 'subsample': 0.6936121294084248, 'colsample_bytree': 0.8222739392872015, 'reg_alpha': 3.526584988940363e-06, 'reg_lambda': 0.0016555551509239532, 'scale_pos_weight': 1.3283764168153238}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:46:10,617] Trial 42 finished with value: 0.916195275199984 and parameters: {'max_depth': 4, 'learning_rate': 0.05803084031463036, 'min_child_weight': 18, 'gamma': 2.0416036108507756, 'subsample': 0.6844367930257835, 'colsample_bytree': 0.8730016790165347, 'reg_alpha': 8.089966470155115e-06, 'reg_lambda': 0.009121722456604373, 'scale_pos_weight': 0.7769181364302139}. Best is trial 24 with value: 0.9162104682973672.
[I 2026-03-24 08:46:48,487] Trial 43 finished with value: 0.9162766493204086 and parameters: {'max_depth': 4, 'learning_rate': 0.0464162536906739, 'min_child_weight': 17, 'gamma': 1.6308332526987914, 'subsample': 0.647431867444064, 'colsample_bytree': 0.8769545229170373, 'reg_alpha': 4.3548661831192793e-07, 'reg_lambda': 0.011377817984195545, 'scale_pos_weight': 0.5447473561688188}. Best is trial 43 with value: 0.9162766493204086.
[I 2026-03-24 08:47:10,218] Trial 44 finished with value: 0.9020049518202999 and parameters: {'max_depth': 4, 'learning_rate': 0.001090561914826461, 'min_child_weight': 17, 'gamma': 1.6016846918081182, 'subsample': 0.5370364214177105, 'colsample_bytree': 0.9996555762973651, 'reg_alpha': 3.8331433379938364e-07, 'reg_lambda': 0.04229172880216524, 'scale_pos_weight': 0.548980830864053}. Best is trial 43 with value: 0.9162766493204086.

In [21]:
best_params = study.best_trial.params
best_score = study.best_trial.value
print(best_params, best_score)

{'max_depth': 4, 'learning_rate': 0.0464162536906739, 'min_child_weight': 17, 'gamma': 1.6308332526987914, 'subsample': 0.647431867444064, 'colsample_bytree': 0.8769545229170373, 'reg_alpha': 4.3548661831192793e-07, 'reg_lambda': 0.011377817984195545, 'scale_pos_weight': 0.5447473561688188} 0.9162766493204086

In [22]:
best_iter = int(study.best_trial.user_attrs["avg_best_iteration"])

In [23]:
final_model = XGBClassifier(
    **study.best_trial.params,
    objective="binary:logistic",
    eval_metric="auc",
    tree_method="hist",
    random_state=42,
    verbosity=0,
    device="cuda",
    n_estimators=best_iter
)

final_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8769545229170373, device='cuda',
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='auc', feature_types=None, feature_weights=None,
              gamma=1.6308332526987914, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.0464162536906739,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=17, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=2421, n_jobs=None,
              num_parallel_tree=None, ...)

In [24]:
test_proba = final_model.predict_proba(test)[:, 1]

In [25]:
submission = pd.DataFrame({
    "id": test_id,
    "Churn": test_proba
})
submission.to_csv("submission.csv", index=False)